# environment.yml
name: MfdGCN_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - "jax[cuda12]"
    - morphomatics
    - numpy
    - flax
    - optax
    - jraph
    - pyvista
    - networkx
    - sckit-learn